### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/zerif-update-fix#1]
@rodica-andronache I'm seeing this error when plugin is activated

![image](https://cloud.githubusercontent.com/assets/10324144/20028054/44dd3d7c-a2fd-11e6-83be-a2f10f387496.png)

**Comment by rodica-andronache** [comment]
@UVLabs I don't think this is related to the plugin, because we don't use any of those constants. I think it may be related to your localhost install. Can you please try on another install?

**Comment by UVLabs** [comment]
might be on my end dont see it anymore
